### ISSUE TITLE
[bug] remove touch event for date when user scrolling the page

### ISSUE THREAD

**Issue by hux2** [get6/get912000won#14]
## 📢 Description

현재 모바일 환경에서는 click event 대신 touch event로 날짜 버튼을 컨트롤하고 있습니다.
iOS 환경의 모바일 브라우저에는 magnifying glass 라는 기능이 있는데요. 이 기능 때문에 달력의 날짜 버튼에 오작동이 발생하여 이를 방지하기 위한 까닭입니다.
그런데, 사용자가 페이지를 스크롤하기 위해 달력 부분을 터치해서 움직이면 터치가 발생한 곳의 날짜가 의도치 않게 선택 / 선택해제가 되어버립니다.

원래는 touchStart event와 touchEnd event 사이에 touchMove event가 발생하면 click event로 이어지지 않고, touchMove event가 없어야만 click event가 발생하여 버튼이 제대로 동작합니다. 
하지만 우리 달력의 날짜 버튼은 (모바일 환경에서만) touch event로 제어되기 때문에, 사용자의 touch가 스크롤을 위한 것인지, 날짜 버튼 선택을 위한 것인지 개발자가 구분해내야 합니다. 

이전 커밋에서 이를 방지하기 위한 로직을 넣었으나 이번엔 갤럭시 디바이스에서 터치가 먹통이 되는 문제가 발생하더군요.
따라서 운영체제나 기종에 상관없이 문제가 발생하지 않으면서도 select와 scroll을 구분할 수 있는 방법을 찾아보려 합니다.

## 💎 Requirements

사용자의 터치가 날짜 선택인지, 스크롤링인지에 따라 올바르게 작동하도록 코드 수정하기
모바일 환경에서 실제로 페이지가 스크롤 되었는지를 알 수 있는 방법이 있다면 좋을텐데.. 찾아봅시다.

## ✨ Todo

- [x] 날짜 선택을 위한 터치에만 날짜 버튼이 작동하도록 하고, 스크롤링 할 때에는 버튼이 동작하지 않도록 할 것
- [x] 운영체제나 기기와 상관없이 의도대로 동작하는지 충분히 테스트할 것

## 🐣 ETC

쉽게만 생각했는데.. 
생각보다 까다롭군요.

나아가서, 손가락으로 쓸면서 날짜를 한 번에 선택할 수 있도록 구현하는 방법도 같이 고려해보면 좋을 것 같군요.

**Comment by get6** [comment]
수고하셨습니다욧!
