### ISSUE TITLE
[bug] Icon does not change in dark mode

### ISSUE THREAD

**Issue by get6** [get6/get912000won#7]
## 📢 Description

다크모드 아이콘을 두번 눌러야 바뀝니다.
그 뒤로는 정상적으로 동작합니다.
제 생각에는 초기 값이 세팅되어 있지 않아서 그런 것 같습니다!

## 💎 Requirements

처음에 theme이 빈값이라면 시스템 설정을 따라가기 (되는지 확인)
가능하다면 로컬스토리지나 쿠키로 테마 설정 저장해두기 (브라우저가 알아서 하고 있는지 모르겠음ㅜ)

## ✨ Todo

- [x] 오류 파악하기
- [x] 테스트하기

## 🐣 ETC

갓hhwang

**Comment by hux2** [comment]
next-themes 라이브러리의 themeprovider는 브라우저의 localstorage에서 theme 정보를 저장하고, 불러옵니다.
페이지가 새로고침 되었을 때, 서버에서 렌더링 과정을 다시 거치게 되는데 서버 측에서는 브라우저의 localstorage에 접근할 수 없습니다. 
따라서 theme 정보를 가져오지 못해 값이 undefined가 됩니다.
우리 사이트는 theme 값에 따라 어떤 토글 아이콘을 렌더링할지 결정하게 되는데, theme의 값이 undefined라면 적절한 토글 아이콘을 렌더링하지 못하게 됩니다. 이를 hydration mismatch error라고 합니다. (출처 : https://www.npmjs.com/package/next-themes#avoid-hydration-mismatch)

따라서 react의 useEffect를 사용하여, 컴포넌트가 제대로 마운트된 이후 theme 값을 불러오도록 적용했습니다.
조금 더 유려하게 코드를 처리하고 싶은데, 그러면 next-themes 라이브러리를 쓰지 않고 제가 직접 theme mode 기능을 구현해야 할 것 같네요.
일단 발생한 문제를 고치는게 우선이기 때문에 현재와 같이 처리하고, refactoring은 조금 더 공부한 뒤 진행하겠습니다. :)
